# Generated by Django 3.1.4 on 2021-02-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=100)),
                ('tricode', models.CharField(max_length=3)),
                ('names', models.JSONField()),
                ('stats', models.JSONField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
    ]
