# Generated by Django 3.1.4 on 2021-01-01 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttoscore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanduelodds',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2021, 1, 1)),
        ),
    ]
