# Generated by Django 3.1.4 on 2021-01-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttoscore', '0002_auto_20210101_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanduelodds',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
