# Generated by Django 3.1.4 on 2021-01-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttoscore', '0004_firstscorer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstscorer',
            name='number_of_times',
            field=models.IntegerField(blank=True),
        ),
    ]
