# Generated by Django 3.1.4 on 2021-01-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttoscore', '0005_auto_20210101_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstscorer',
            name='number_of_times',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
