# Generated by Django 3.1.4 on 2021-02-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nba_id', models.IntegerField()),
                ('fd_id', models.IntegerField(null=1)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('team_id', models.CharField(max_length=100)),
                ('prev_teams', models.JSONField()),
                ('is_jumper', models.BooleanField(default=0)),
                ('jumps_jumped', models.IntegerField(default=0)),
                ('jumps_won', models.IntegerField(default=0)),
                ('elo_score', models.FloatField(default=1500)),
                ('last_update', models.DateTimeField()),
            ],
        ),
    ]
