# Generated by Django 3.1.7 on 2021-02-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttoscore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='a_team',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_date',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_time',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='game',
            name='h_team',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='game',
            name='tricode',
            field=models.CharField(max_length=25),
        ),
    ]
