# Generated by Django 3.1.4 on 2021-02-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firsttoscore', '0002_auto_20210220_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamToScoreFirstOdds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odds', models.FloatField(default=0)),
                ('game_time', models.CharField(max_length=25)),
                ('fanduel_event_id', models.FloatField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firsttoscore.team')),
            ],
        ),
    ]
