# Generated by Django 3.1.4 on 2021-02-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttoscore', '0004_auto_20210228_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='odds',
            new_name='a_odds',
        ),
        migrations.AddField(
            model_name='game',
            name='h_odds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
