# Generated by Django 3.1.4 on 2021-02-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttoscore', '0006_game_fd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='projected_starters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
