# Generated by Django 4.0.4 on 2022-05-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttoscore', '0007_game_projected_starters'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='colors',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='team',
            name='names',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='team',
            name='stats',
            field=models.JSONField(default=list),
        ),
    ]
