# Generated by Django 3.1.4 on 2021-02-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('game_id', models.CharField(max_length=15)),
                ('game_utc', models.DateTimeField()),
                ('game_date', models.CharField(max_length=8)),
                ('stage', models.IntegerField()),
                ('tricode', models.CharField(max_length=6)),
                ('h_team', models.CharField(max_length=15)),
                ('a_team', models.CharField(max_length=15)),
                ('jumpers', models.JSONField()),
                ('jump_win', models.IntegerField()),
                ('team_first_score', models.IntegerField()),
                ('player_first_score', models.IntegerField()),
                ('all_first_scorers', models.JSONField()),
                ('all_first_shooters', models.JSONField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
    ]
